name: Create Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build Multi platform release artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Check Cargo.toml version matches tag
        shell: bash
        run: |
          TAG_VERSION=${GITHUB_REF##*/}
          CARGO_VERSION=$(grep '^version =' Cargo.toml | head -n1 | sed -E 's/version = "(.*)"/\1/')
          echo "Tag version: $TAG_VERSION"
          echo "Cargo.toml version: $CARGO_VERSION"
          if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
            echo "Error: Tag version does not match Cargo.toml version"
            exit 1
          fi

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build project in release mode
        run: cargo build --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-${{ matrix.os }}
          path: |
            target/release/snake
            target/release/snake.exe

  release:
    name: Create Release from Tag
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: release_binaries

      - name: Extract tag message
        id: tag_message
        run: |
          echo "BODY<<EOF" >> $GITHUB_OUTPUT
          git tag -l --format='%(contents)' ${{ github.ref_name }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.tag_message.outputs.BODY }}
          files: release_binaries/*/*
          overwrite_files: true
